//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA_RAC_Form_App.CarService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarRequest", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.RequestObjects")]
    [System.SerializableAttribute()]
    public partial class CarRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DailyMaxKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DriverAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA_RAC_Form_App.CarService.AirgBagEnum HasAirBagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LagguageVolumeMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LicenceAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DailyMaxKm {
            get {
                return this.DailyMaxKmField;
            }
            set {
                if ((this.DailyMaxKmField.Equals(value) != true)) {
                    this.DailyMaxKmField = value;
                    this.RaisePropertyChanged("DailyMaxKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriverAge {
            get {
                return this.DriverAgeField;
            }
            set {
                if ((this.DriverAgeField.Equals(value) != true)) {
                    this.DriverAgeField = value;
                    this.RaisePropertyChanged("DriverAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA_RAC_Form_App.CarService.AirgBagEnum HasAirBag {
            get {
                return this.HasAirBagField;
            }
            set {
                if ((this.HasAirBagField.Equals(value) != true)) {
                    this.HasAirBagField = value;
                    this.RaisePropertyChanged("HasAirBag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LagguageVolumeMin {
            get {
                return this.LagguageVolumeMinField;
            }
            set {
                if ((this.LagguageVolumeMinField.Equals(value) != true)) {
                    this.LagguageVolumeMinField = value;
                    this.RaisePropertyChanged("LagguageVolumeMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LicenceAge {
            get {
                return this.LicenceAgeField;
            }
            set {
                if ((this.LicenceAgeField.Equals(value) != true)) {
                    this.LicenceAgeField = value;
                    this.RaisePropertyChanged("LicenceAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSeats {
            get {
                return this.NumSeatsField;
            }
            set {
                if ((this.NumSeatsField.Equals(value) != true)) {
                    this.NumSeatsField = value;
                    this.RaisePropertyChanged("NumSeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentPrice {
            get {
                return this.RentPriceField;
            }
            set {
                if ((this.RentPriceField.Equals(value) != true)) {
                    this.RentPriceField = value;
                    this.RaisePropertyChanged("RentPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AirgBagEnum", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.Enums")]
    public enum AirgBagEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoMatter = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.Models")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DailyMaxKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DriverAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA_RAC_Form_App.CarService.AirgBagEnum HasAirBagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LicenceAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LuggageVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentKm {
            get {
                return this.CurrentKmField;
            }
            set {
                if ((this.CurrentKmField.Equals(value) != true)) {
                    this.CurrentKmField = value;
                    this.RaisePropertyChanged("CurrentKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DailyMaxKm {
            get {
                return this.DailyMaxKmField;
            }
            set {
                if ((this.DailyMaxKmField.Equals(value) != true)) {
                    this.DailyMaxKmField = value;
                    this.RaisePropertyChanged("DailyMaxKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriverAge {
            get {
                return this.DriverAgeField;
            }
            set {
                if ((this.DriverAgeField.Equals(value) != true)) {
                    this.DriverAgeField = value;
                    this.RaisePropertyChanged("DriverAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA_RAC_Form_App.CarService.AirgBagEnum HasAirBag {
            get {
                return this.HasAirBagField;
            }
            set {
                if ((this.HasAirBagField.Equals(value) != true)) {
                    this.HasAirBagField = value;
                    this.RaisePropertyChanged("HasAirBag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LicenceAge {
            get {
                return this.LicenceAgeField;
            }
            set {
                if ((this.LicenceAgeField.Equals(value) != true)) {
                    this.LicenceAgeField = value;
                    this.RaisePropertyChanged("LicenceAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LuggageVolume {
            get {
                return this.LuggageVolumeField;
            }
            set {
                if ((this.LuggageVolumeField.Equals(value) != true)) {
                    this.LuggageVolumeField = value;
                    this.RaisePropertyChanged("LuggageVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSeats {
            get {
                return this.NumSeatsField;
            }
            set {
                if ((this.NumSeatsField.Equals(value) != true)) {
                    this.NumSeatsField = value;
                    this.RaisePropertyChanged("NumSeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentPrice {
            get {
                return this.RentPriceField;
            }
            set {
                if ((this.RentPriceField.Equals(value) != true)) {
                    this.RentPriceField = value;
                    this.RaisePropertyChanged("RentPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarService.ICars")]
    public interface ICars {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/ListCars", ReplyAction="http://tempuri.org/ICars/ListCarsResponse")]
        SOA_RAC_Form_App.CarService.Car[] ListCars(SOA_RAC_Form_App.CarService.CarRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/ListCars", ReplyAction="http://tempuri.org/ICars/ListCarsResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.CarService.Car[]> ListCarsAsync(SOA_RAC_Form_App.CarService.CarRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/CreateCar", ReplyAction="http://tempuri.org/ICars/CreateCarResponse")]
        SOA_RAC_Form_App.CarService.Car CreateCar(SOA_RAC_Form_App.CarService.Car Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/CreateCar", ReplyAction="http://tempuri.org/ICars/CreateCarResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.CarService.Car> CreateCarAsync(SOA_RAC_Form_App.CarService.Car Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/GetCar", ReplyAction="http://tempuri.org/ICars/GetCarResponse")]
        SOA_RAC_Form_App.CarService.Car GetCar(int CardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/GetCar", ReplyAction="http://tempuri.org/ICars/GetCarResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.CarService.Car> GetCarAsync(int CardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/UpdateCar", ReplyAction="http://tempuri.org/ICars/UpdateCarResponse")]
        SOA_RAC_Form_App.CarService.Car UpdateCar(SOA_RAC_Form_App.CarService.Car Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/UpdateCar", ReplyAction="http://tempuri.org/ICars/UpdateCarResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.CarService.Car> UpdateCarAsync(SOA_RAC_Form_App.CarService.Car Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/DeleteCar", ReplyAction="http://tempuri.org/ICars/DeleteCarResponse")]
        SOA_RAC_Form_App.CarService.Car DeleteCar(int CardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/DeleteCar", ReplyAction="http://tempuri.org/ICars/DeleteCarResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.CarService.Car> DeleteCarAsync(int CardId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarsChannel : SOA_RAC_Form_App.CarService.ICars, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarsClient : System.ServiceModel.ClientBase<SOA_RAC_Form_App.CarService.ICars>, SOA_RAC_Form_App.CarService.ICars {
        
        public CarsClient() {
        }
        
        public CarsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOA_RAC_Form_App.CarService.Car[] ListCars(SOA_RAC_Form_App.CarService.CarRequest Request) {
            return base.Channel.ListCars(Request);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.CarService.Car[]> ListCarsAsync(SOA_RAC_Form_App.CarService.CarRequest Request) {
            return base.Channel.ListCarsAsync(Request);
        }
        
        public SOA_RAC_Form_App.CarService.Car CreateCar(SOA_RAC_Form_App.CarService.Car Entyity) {
            return base.Channel.CreateCar(Entyity);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.CarService.Car> CreateCarAsync(SOA_RAC_Form_App.CarService.Car Entyity) {
            return base.Channel.CreateCarAsync(Entyity);
        }
        
        public SOA_RAC_Form_App.CarService.Car GetCar(int CardId) {
            return base.Channel.GetCar(CardId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.CarService.Car> GetCarAsync(int CardId) {
            return base.Channel.GetCarAsync(CardId);
        }
        
        public SOA_RAC_Form_App.CarService.Car UpdateCar(SOA_RAC_Form_App.CarService.Car Entyity) {
            return base.Channel.UpdateCar(Entyity);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.CarService.Car> UpdateCarAsync(SOA_RAC_Form_App.CarService.Car Entyity) {
            return base.Channel.UpdateCarAsync(Entyity);
        }
        
        public SOA_RAC_Form_App.CarService.Car DeleteCar(int CardId) {
            return base.Channel.DeleteCar(CardId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.CarService.Car> DeleteCarAsync(int CardId) {
            return base.Channel.DeleteCarAsync(CardId);
        }
    }
}
