//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA_RAC_Form_App.RAC_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarRequest", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.RequestObjects")]
    [System.SerializableAttribute()]
    public partial class CarRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DailyMaxKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DriverAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA_RAC_Form_App.RAC_Service.AirgBagEnum HasAirBagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LagguageVolumeMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LicenceAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DailyMaxKm {
            get {
                return this.DailyMaxKmField;
            }
            set {
                if ((this.DailyMaxKmField.Equals(value) != true)) {
                    this.DailyMaxKmField = value;
                    this.RaisePropertyChanged("DailyMaxKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriverAge {
            get {
                return this.DriverAgeField;
            }
            set {
                if ((this.DriverAgeField.Equals(value) != true)) {
                    this.DriverAgeField = value;
                    this.RaisePropertyChanged("DriverAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA_RAC_Form_App.RAC_Service.AirgBagEnum HasAirBag {
            get {
                return this.HasAirBagField;
            }
            set {
                if ((this.HasAirBagField.Equals(value) != true)) {
                    this.HasAirBagField = value;
                    this.RaisePropertyChanged("HasAirBag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LagguageVolumeMin {
            get {
                return this.LagguageVolumeMinField;
            }
            set {
                if ((this.LagguageVolumeMinField.Equals(value) != true)) {
                    this.LagguageVolumeMinField = value;
                    this.RaisePropertyChanged("LagguageVolumeMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LicenceAge {
            get {
                return this.LicenceAgeField;
            }
            set {
                if ((this.LicenceAgeField.Equals(value) != true)) {
                    this.LicenceAgeField = value;
                    this.RaisePropertyChanged("LicenceAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSeats {
            get {
                return this.NumSeatsField;
            }
            set {
                if ((this.NumSeatsField.Equals(value) != true)) {
                    this.NumSeatsField = value;
                    this.RaisePropertyChanged("NumSeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentPrice {
            get {
                return this.RentPriceField;
            }
            set {
                if ((this.RentPriceField.Equals(value) != true)) {
                    this.RentPriceField = value;
                    this.RaisePropertyChanged("RentPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AirgBagEnum", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.Enums")]
    public enum AirgBagEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoMatter = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.Models")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CurrentKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DailyMaxKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DriverAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA_RAC_Form_App.RAC_Service.AirgBagEnum HasAirBagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LicenceAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LuggageVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RentPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CurrentKm {
            get {
                return this.CurrentKmField;
            }
            set {
                if ((this.CurrentKmField.Equals(value) != true)) {
                    this.CurrentKmField = value;
                    this.RaisePropertyChanged("CurrentKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DailyMaxKm {
            get {
                return this.DailyMaxKmField;
            }
            set {
                if ((this.DailyMaxKmField.Equals(value) != true)) {
                    this.DailyMaxKmField = value;
                    this.RaisePropertyChanged("DailyMaxKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriverAge {
            get {
                return this.DriverAgeField;
            }
            set {
                if ((this.DriverAgeField.Equals(value) != true)) {
                    this.DriverAgeField = value;
                    this.RaisePropertyChanged("DriverAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA_RAC_Form_App.RAC_Service.AirgBagEnum HasAirBag {
            get {
                return this.HasAirBagField;
            }
            set {
                if ((this.HasAirBagField.Equals(value) != true)) {
                    this.HasAirBagField = value;
                    this.RaisePropertyChanged("HasAirBag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LicenceAge {
            get {
                return this.LicenceAgeField;
            }
            set {
                if ((this.LicenceAgeField.Equals(value) != true)) {
                    this.LicenceAgeField = value;
                    this.RaisePropertyChanged("LicenceAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LuggageVolume {
            get {
                return this.LuggageVolumeField;
            }
            set {
                if ((this.LuggageVolumeField.Equals(value) != true)) {
                    this.LuggageVolumeField = value;
                    this.RaisePropertyChanged("LuggageVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSeats {
            get {
                return this.NumSeatsField;
            }
            set {
                if ((this.NumSeatsField.Equals(value) != true)) {
                    this.NumSeatsField = value;
                    this.RaisePropertyChanged("NumSeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RentPrice {
            get {
                return this.RentPriceField;
            }
            set {
                if ((this.RentPriceField.Equals(value) != true)) {
                    this.RentPriceField = value;
                    this.RaisePropertyChanged("RentPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AviableCarRequest", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.RequestObjects")]
    [System.SerializableAttribute()]
    public partial class AviableCarRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateBeginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DriverAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LicenceAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumDaysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateBegin {
            get {
                return this.DateBeginField;
            }
            set {
                if ((this.DateBeginField.Equals(value) != true)) {
                    this.DateBeginField = value;
                    this.RaisePropertyChanged("DateBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriverAge {
            get {
                return this.DriverAgeField;
            }
            set {
                if ((this.DriverAgeField.Equals(value) != true)) {
                    this.DriverAgeField = value;
                    this.RaisePropertyChanged("DriverAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LicenceAge {
            get {
                return this.LicenceAgeField;
            }
            set {
                if ((this.LicenceAgeField.Equals(value) != true)) {
                    this.LicenceAgeField = value;
                    this.RaisePropertyChanged("LicenceAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumDays {
            get {
                return this.NumDaysField;
            }
            set {
                if ((this.NumDaysField.Equals(value) != true)) {
                    this.NumDaysField = value;
                    this.RaisePropertyChanged("NumDays");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerRequest", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.RequestObjects")]
    [System.SerializableAttribute()]
    public partial class CustomerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DriverAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LicenceAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriverAge {
            get {
                return this.DriverAgeField;
            }
            set {
                if ((this.DriverAgeField.Equals(value) != true)) {
                    this.DriverAgeField = value;
                    this.RaisePropertyChanged("DriverAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LicenceAge {
            get {
                return this.LicenceAgeField;
            }
            set {
                if ((this.LicenceAgeField.Equals(value) != true)) {
                    this.LicenceAgeField = value;
                    this.RaisePropertyChanged("LicenceAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.Models")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DriverAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LicenceAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriverAge {
            get {
                return this.DriverAgeField;
            }
            set {
                if ((this.DriverAgeField.Equals(value) != true)) {
                    this.DriverAgeField = value;
                    this.RaisePropertyChanged("DriverAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LicenceAge {
            get {
                return this.LicenceAgeField;
            }
            set {
                if ((this.LicenceAgeField.Equals(value) != true)) {
                    this.LicenceAgeField = value;
                    this.RaisePropertyChanged("LicenceAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyRequest", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.RequestObjects")]
    [System.SerializableAttribute()]
    public partial class CompanyRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumCarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumCars {
            get {
                return this.NumCarsField;
            }
            set {
                if ((this.NumCarsField.Equals(value) != true)) {
                    this.NumCarsField = value;
                    this.RaisePropertyChanged("NumCars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.Models")]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumCarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumCars {
            get {
                return this.NumCarsField;
            }
            set {
                if ((this.NumCarsField.Equals(value) != true)) {
                    this.NumCarsField = value;
                    this.RaisePropertyChanged("NumCars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.RequestObjects")]
    [System.SerializableAttribute()]
    public partial class TransactionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateBeginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReturnKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReturnedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarId {
            get {
                return this.CarIdField;
            }
            set {
                if ((this.CarIdField.Equals(value) != true)) {
                    this.CarIdField = value;
                    this.RaisePropertyChanged("CarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentKm {
            get {
                return this.CurrentKmField;
            }
            set {
                if ((this.CurrentKmField.Equals(value) != true)) {
                    this.CurrentKmField = value;
                    this.RaisePropertyChanged("CurrentKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateBegin {
            get {
                return this.DateBeginField;
            }
            set {
                if ((this.DateBeginField.Equals(value) != true)) {
                    this.DateBeginField = value;
                    this.RaisePropertyChanged("DateBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumDays {
            get {
                return this.NumDaysField;
            }
            set {
                if ((this.NumDaysField.Equals(value) != true)) {
                    this.NumDaysField = value;
                    this.RaisePropertyChanged("NumDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnKm {
            get {
                return this.ReturnKmField;
            }
            set {
                if ((this.ReturnKmField.Equals(value) != true)) {
                    this.ReturnKmField = value;
                    this.RaisePropertyChanged("ReturnKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Returned {
            get {
                return this.ReturnedField;
            }
            set {
                if ((this.ReturnedField.Equals(value) != true)) {
                    this.ReturnedField = value;
                    this.RaisePropertyChanged("Returned");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.Models")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateBeginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReturnKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReturnedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarId {
            get {
                return this.CarIdField;
            }
            set {
                if ((this.CarIdField.Equals(value) != true)) {
                    this.CarIdField = value;
                    this.RaisePropertyChanged("CarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentKm {
            get {
                return this.CurrentKmField;
            }
            set {
                if ((this.CurrentKmField.Equals(value) != true)) {
                    this.CurrentKmField = value;
                    this.RaisePropertyChanged("CurrentKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateBegin {
            get {
                return this.DateBeginField;
            }
            set {
                if ((this.DateBeginField.Equals(value) != true)) {
                    this.DateBeginField = value;
                    this.RaisePropertyChanged("DateBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumDays {
            get {
                return this.NumDaysField;
            }
            set {
                if ((this.NumDaysField.Equals(value) != true)) {
                    this.NumDaysField = value;
                    this.RaisePropertyChanged("NumDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnKm {
            get {
                return this.ReturnKmField;
            }
            set {
                if ((this.ReturnKmField.Equals(value) != true)) {
                    this.ReturnKmField = value;
                    this.RaisePropertyChanged("ReturnKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Returned {
            get {
                return this.ReturnedField;
            }
            set {
                if ((this.ReturnedField.Equals(value) != true)) {
                    this.ReturnedField = value;
                    this.RaisePropertyChanged("Returned");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRequest", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.RequestObjects")]
    [System.SerializableAttribute()]
    public partial class UserRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberRoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumberRole {
            get {
                return this.PhoneNumberRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberRoleField, value) != true)) {
                    this.PhoneNumberRoleField = value;
                    this.RaisePropertyChanged("PhoneNumberRole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.Models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOA_RAC_Form_App.RAC_Service.RoleEnum RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOA_RAC_Form_App.RAC_Service.RoleEnum Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleEnum", Namespace="http://schemas.datacontract.org/2004/07/SOAAssignment.Enums")]
    public enum RoleEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Employee = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RAC_Service.ICars")]
    public interface ICars {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/ListCars", ReplyAction="http://tempuri.org/ICars/ListCarsResponse")]
        SOA_RAC_Form_App.RAC_Service.Car[] ListCars(SOA_RAC_Form_App.RAC_Service.CarRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/ListCars", ReplyAction="http://tempuri.org/ICars/ListCarsResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car[]> ListCarsAsync(SOA_RAC_Form_App.RAC_Service.CarRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/CreateCar", ReplyAction="http://tempuri.org/ICars/CreateCarResponse")]
        SOA_RAC_Form_App.RAC_Service.Car CreateCar(SOA_RAC_Form_App.RAC_Service.Car Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/CreateCar", ReplyAction="http://tempuri.org/ICars/CreateCarResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car> CreateCarAsync(SOA_RAC_Form_App.RAC_Service.Car Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/GetCar", ReplyAction="http://tempuri.org/ICars/GetCarResponse")]
        SOA_RAC_Form_App.RAC_Service.Car GetCar(int CardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/GetCar", ReplyAction="http://tempuri.org/ICars/GetCarResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car> GetCarAsync(int CardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/UpdateCar", ReplyAction="http://tempuri.org/ICars/UpdateCarResponse")]
        SOA_RAC_Form_App.RAC_Service.Car UpdateCar(SOA_RAC_Form_App.RAC_Service.Car Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/UpdateCar", ReplyAction="http://tempuri.org/ICars/UpdateCarResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car> UpdateCarAsync(SOA_RAC_Form_App.RAC_Service.Car Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/DeleteCar", ReplyAction="http://tempuri.org/ICars/DeleteCarResponse")]
        SOA_RAC_Form_App.RAC_Service.Car DeleteCar(int CardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/DeleteCar", ReplyAction="http://tempuri.org/ICars/DeleteCarResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car> DeleteCarAsync(int CardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/ListAvailableCars", ReplyAction="http://tempuri.org/ICars/ListAvailableCarsResponse")]
        SOA_RAC_Form_App.RAC_Service.Car[] ListAvailableCars(SOA_RAC_Form_App.RAC_Service.AviableCarRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICars/ListAvailableCars", ReplyAction="http://tempuri.org/ICars/ListAvailableCarsResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car[]> ListAvailableCarsAsync(SOA_RAC_Form_App.RAC_Service.AviableCarRequest Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarsChannel : SOA_RAC_Form_App.RAC_Service.ICars, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarsClient : System.ServiceModel.ClientBase<SOA_RAC_Form_App.RAC_Service.ICars>, SOA_RAC_Form_App.RAC_Service.ICars {
        
        public CarsClient() {
        }
        
        public CarsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOA_RAC_Form_App.RAC_Service.Car[] ListCars(SOA_RAC_Form_App.RAC_Service.CarRequest Request) {
            return base.Channel.ListCars(Request);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car[]> ListCarsAsync(SOA_RAC_Form_App.RAC_Service.CarRequest Request) {
            return base.Channel.ListCarsAsync(Request);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Car CreateCar(SOA_RAC_Form_App.RAC_Service.Car Entyity) {
            return base.Channel.CreateCar(Entyity);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car> CreateCarAsync(SOA_RAC_Form_App.RAC_Service.Car Entyity) {
            return base.Channel.CreateCarAsync(Entyity);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Car GetCar(int CardId) {
            return base.Channel.GetCar(CardId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car> GetCarAsync(int CardId) {
            return base.Channel.GetCarAsync(CardId);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Car UpdateCar(SOA_RAC_Form_App.RAC_Service.Car Entyity) {
            return base.Channel.UpdateCar(Entyity);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car> UpdateCarAsync(SOA_RAC_Form_App.RAC_Service.Car Entyity) {
            return base.Channel.UpdateCarAsync(Entyity);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Car DeleteCar(int CardId) {
            return base.Channel.DeleteCar(CardId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car> DeleteCarAsync(int CardId) {
            return base.Channel.DeleteCarAsync(CardId);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Car[] ListAvailableCars(SOA_RAC_Form_App.RAC_Service.AviableCarRequest Request) {
            return base.Channel.ListAvailableCars(Request);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Car[]> ListAvailableCarsAsync(SOA_RAC_Form_App.RAC_Service.AviableCarRequest Request) {
            return base.Channel.ListAvailableCarsAsync(Request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RAC_Service.ICustomers")]
    public interface ICustomers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/ListCustomers", ReplyAction="http://tempuri.org/ICustomers/ListCustomersResponse")]
        SOA_RAC_Form_App.RAC_Service.Customer[] ListCustomers(SOA_RAC_Form_App.RAC_Service.CustomerRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/ListCustomers", ReplyAction="http://tempuri.org/ICustomers/ListCustomersResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Customer[]> ListCustomersAsync(SOA_RAC_Form_App.RAC_Service.CustomerRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/CreateCustomer", ReplyAction="http://tempuri.org/ICustomers/CreateCustomerResponse")]
        SOA_RAC_Form_App.RAC_Service.Customer CreateCustomer(SOA_RAC_Form_App.RAC_Service.Customer Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/CreateCustomer", ReplyAction="http://tempuri.org/ICustomers/CreateCustomerResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Customer> CreateCustomerAsync(SOA_RAC_Form_App.RAC_Service.Customer Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/GetCustomer", ReplyAction="http://tempuri.org/ICustomers/GetCustomerResponse")]
        SOA_RAC_Form_App.RAC_Service.Customer GetCustomer(int CustomerdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/GetCustomer", ReplyAction="http://tempuri.org/ICustomers/GetCustomerResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Customer> GetCustomerAsync(int CustomerdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/UpdateCustomer", ReplyAction="http://tempuri.org/ICustomers/UpdateCustomerResponse")]
        SOA_RAC_Form_App.RAC_Service.Customer UpdateCustomer(SOA_RAC_Form_App.RAC_Service.Customer Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/UpdateCustomer", ReplyAction="http://tempuri.org/ICustomers/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Customer> UpdateCustomerAsync(SOA_RAC_Form_App.RAC_Service.Customer Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/DeleteCustomer", ReplyAction="http://tempuri.org/ICustomers/DeleteCustomerResponse")]
        SOA_RAC_Form_App.RAC_Service.Customer DeleteCustomer(int CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomers/DeleteCustomer", ReplyAction="http://tempuri.org/ICustomers/DeleteCustomerResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Customer> DeleteCustomerAsync(int CustomerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomersChannel : SOA_RAC_Form_App.RAC_Service.ICustomers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomersClient : System.ServiceModel.ClientBase<SOA_RAC_Form_App.RAC_Service.ICustomers>, SOA_RAC_Form_App.RAC_Service.ICustomers {
        
        public CustomersClient() {
        }
        
        public CustomersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOA_RAC_Form_App.RAC_Service.Customer[] ListCustomers(SOA_RAC_Form_App.RAC_Service.CustomerRequest Request) {
            return base.Channel.ListCustomers(Request);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Customer[]> ListCustomersAsync(SOA_RAC_Form_App.RAC_Service.CustomerRequest Request) {
            return base.Channel.ListCustomersAsync(Request);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Customer CreateCustomer(SOA_RAC_Form_App.RAC_Service.Customer Entyity) {
            return base.Channel.CreateCustomer(Entyity);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Customer> CreateCustomerAsync(SOA_RAC_Form_App.RAC_Service.Customer Entyity) {
            return base.Channel.CreateCustomerAsync(Entyity);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Customer GetCustomer(int CustomerdId) {
            return base.Channel.GetCustomer(CustomerdId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Customer> GetCustomerAsync(int CustomerdId) {
            return base.Channel.GetCustomerAsync(CustomerdId);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Customer UpdateCustomer(SOA_RAC_Form_App.RAC_Service.Customer Entyity) {
            return base.Channel.UpdateCustomer(Entyity);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Customer> UpdateCustomerAsync(SOA_RAC_Form_App.RAC_Service.Customer Entyity) {
            return base.Channel.UpdateCustomerAsync(Entyity);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Customer DeleteCustomer(int CustomerId) {
            return base.Channel.DeleteCustomer(CustomerId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Customer> DeleteCustomerAsync(int CustomerId) {
            return base.Channel.DeleteCustomerAsync(CustomerId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RAC_Service.ICompanies")]
    public interface ICompanies {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanies/ListCompanies", ReplyAction="http://tempuri.org/ICompanies/ListCompaniesResponse")]
        SOA_RAC_Form_App.RAC_Service.Company[] ListCompanies(SOA_RAC_Form_App.RAC_Service.CompanyRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanies/ListCompanies", ReplyAction="http://tempuri.org/ICompanies/ListCompaniesResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Company[]> ListCompaniesAsync(SOA_RAC_Form_App.RAC_Service.CompanyRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanies/CreateCompany", ReplyAction="http://tempuri.org/ICompanies/CreateCompanyResponse")]
        SOA_RAC_Form_App.RAC_Service.Company CreateCompany(SOA_RAC_Form_App.RAC_Service.Company Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanies/CreateCompany", ReplyAction="http://tempuri.org/ICompanies/CreateCompanyResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Company> CreateCompanyAsync(SOA_RAC_Form_App.RAC_Service.Company Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanies/GetCompany", ReplyAction="http://tempuri.org/ICompanies/GetCompanyResponse")]
        SOA_RAC_Form_App.RAC_Service.Company GetCompany(int CompanydId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanies/GetCompany", ReplyAction="http://tempuri.org/ICompanies/GetCompanyResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Company> GetCompanyAsync(int CompanydId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanies/UpdateCompany", ReplyAction="http://tempuri.org/ICompanies/UpdateCompanyResponse")]
        SOA_RAC_Form_App.RAC_Service.Company UpdateCompany(SOA_RAC_Form_App.RAC_Service.Company Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanies/UpdateCompany", ReplyAction="http://tempuri.org/ICompanies/UpdateCompanyResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Company> UpdateCompanyAsync(SOA_RAC_Form_App.RAC_Service.Company Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanies/DeleteCompany", ReplyAction="http://tempuri.org/ICompanies/DeleteCompanyResponse")]
        SOA_RAC_Form_App.RAC_Service.Company DeleteCompany(int CompanydId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanies/DeleteCompany", ReplyAction="http://tempuri.org/ICompanies/DeleteCompanyResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Company> DeleteCompanyAsync(int CompanydId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompaniesChannel : SOA_RAC_Form_App.RAC_Service.ICompanies, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompaniesClient : System.ServiceModel.ClientBase<SOA_RAC_Form_App.RAC_Service.ICompanies>, SOA_RAC_Form_App.RAC_Service.ICompanies {
        
        public CompaniesClient() {
        }
        
        public CompaniesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompaniesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompaniesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompaniesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOA_RAC_Form_App.RAC_Service.Company[] ListCompanies(SOA_RAC_Form_App.RAC_Service.CompanyRequest Request) {
            return base.Channel.ListCompanies(Request);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Company[]> ListCompaniesAsync(SOA_RAC_Form_App.RAC_Service.CompanyRequest Request) {
            return base.Channel.ListCompaniesAsync(Request);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Company CreateCompany(SOA_RAC_Form_App.RAC_Service.Company Entyity) {
            return base.Channel.CreateCompany(Entyity);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Company> CreateCompanyAsync(SOA_RAC_Form_App.RAC_Service.Company Entyity) {
            return base.Channel.CreateCompanyAsync(Entyity);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Company GetCompany(int CompanydId) {
            return base.Channel.GetCompany(CompanydId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Company> GetCompanyAsync(int CompanydId) {
            return base.Channel.GetCompanyAsync(CompanydId);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Company UpdateCompany(SOA_RAC_Form_App.RAC_Service.Company Entyity) {
            return base.Channel.UpdateCompany(Entyity);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Company> UpdateCompanyAsync(SOA_RAC_Form_App.RAC_Service.Company Entyity) {
            return base.Channel.UpdateCompanyAsync(Entyity);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Company DeleteCompany(int CompanydId) {
            return base.Channel.DeleteCompany(CompanydId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Company> DeleteCompanyAsync(int CompanydId) {
            return base.Channel.DeleteCompanyAsync(CompanydId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RAC_Service.ITransactions")]
    public interface ITransactions {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactions/ListTransactions", ReplyAction="http://tempuri.org/ITransactions/ListTransactionsResponse")]
        SOA_RAC_Form_App.RAC_Service.Transaction[] ListTransactions(SOA_RAC_Form_App.RAC_Service.TransactionRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactions/ListTransactions", ReplyAction="http://tempuri.org/ITransactions/ListTransactionsResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Transaction[]> ListTransactionsAsync(SOA_RAC_Form_App.RAC_Service.TransactionRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactions/CreateTransaction", ReplyAction="http://tempuri.org/ITransactions/CreateTransactionResponse")]
        SOA_RAC_Form_App.RAC_Service.Transaction CreateTransaction(SOA_RAC_Form_App.RAC_Service.Customer Customer, SOA_RAC_Form_App.RAC_Service.Car Car, System.DateTime DateBegin, int NumDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactions/CreateTransaction", ReplyAction="http://tempuri.org/ITransactions/CreateTransactionResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Transaction> CreateTransactionAsync(SOA_RAC_Form_App.RAC_Service.Customer Customer, SOA_RAC_Form_App.RAC_Service.Car Car, System.DateTime DateBegin, int NumDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactions/GetTransaction", ReplyAction="http://tempuri.org/ITransactions/GetTransactionResponse")]
        SOA_RAC_Form_App.RAC_Service.Transaction GetTransaction(int TransactiondId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactions/GetTransaction", ReplyAction="http://tempuri.org/ITransactions/GetTransactionResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Transaction> GetTransactionAsync(int TransactiondId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactions/UpdateTransaction", ReplyAction="http://tempuri.org/ITransactions/UpdateTransactionResponse")]
        SOA_RAC_Form_App.RAC_Service.Transaction UpdateTransaction(SOA_RAC_Form_App.RAC_Service.Transaction Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactions/UpdateTransaction", ReplyAction="http://tempuri.org/ITransactions/UpdateTransactionResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Transaction> UpdateTransactionAsync(SOA_RAC_Form_App.RAC_Service.Transaction Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactions/DeleteTransaction", ReplyAction="http://tempuri.org/ITransactions/DeleteTransactionResponse")]
        SOA_RAC_Form_App.RAC_Service.Transaction DeleteTransaction(int TransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactions/DeleteTransaction", ReplyAction="http://tempuri.org/ITransactions/DeleteTransactionResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Transaction> DeleteTransactionAsync(int TransactionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransactionsChannel : SOA_RAC_Form_App.RAC_Service.ITransactions, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionsClient : System.ServiceModel.ClientBase<SOA_RAC_Form_App.RAC_Service.ITransactions>, SOA_RAC_Form_App.RAC_Service.ITransactions {
        
        public TransactionsClient() {
        }
        
        public TransactionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOA_RAC_Form_App.RAC_Service.Transaction[] ListTransactions(SOA_RAC_Form_App.RAC_Service.TransactionRequest Request) {
            return base.Channel.ListTransactions(Request);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Transaction[]> ListTransactionsAsync(SOA_RAC_Form_App.RAC_Service.TransactionRequest Request) {
            return base.Channel.ListTransactionsAsync(Request);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Transaction CreateTransaction(SOA_RAC_Form_App.RAC_Service.Customer Customer, SOA_RAC_Form_App.RAC_Service.Car Car, System.DateTime DateBegin, int NumDays) {
            return base.Channel.CreateTransaction(Customer, Car, DateBegin, NumDays);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Transaction> CreateTransactionAsync(SOA_RAC_Form_App.RAC_Service.Customer Customer, SOA_RAC_Form_App.RAC_Service.Car Car, System.DateTime DateBegin, int NumDays) {
            return base.Channel.CreateTransactionAsync(Customer, Car, DateBegin, NumDays);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Transaction GetTransaction(int TransactiondId) {
            return base.Channel.GetTransaction(TransactiondId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Transaction> GetTransactionAsync(int TransactiondId) {
            return base.Channel.GetTransactionAsync(TransactiondId);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Transaction UpdateTransaction(SOA_RAC_Form_App.RAC_Service.Transaction Entyity) {
            return base.Channel.UpdateTransaction(Entyity);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Transaction> UpdateTransactionAsync(SOA_RAC_Form_App.RAC_Service.Transaction Entyity) {
            return base.Channel.UpdateTransactionAsync(Entyity);
        }
        
        public SOA_RAC_Form_App.RAC_Service.Transaction DeleteTransaction(int TransactionId) {
            return base.Channel.DeleteTransaction(TransactionId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.Transaction> DeleteTransactionAsync(int TransactionId) {
            return base.Channel.DeleteTransactionAsync(TransactionId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RAC_Service.IUsers")]
    public interface IUsers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/ListUsers", ReplyAction="http://tempuri.org/IUsers/ListUsersResponse")]
        SOA_RAC_Form_App.RAC_Service.User[] ListUsers(SOA_RAC_Form_App.RAC_Service.UserRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/ListUsers", ReplyAction="http://tempuri.org/IUsers/ListUsersResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.User[]> ListUsersAsync(SOA_RAC_Form_App.RAC_Service.UserRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/CreateUser", ReplyAction="http://tempuri.org/IUsers/CreateUserResponse")]
        SOA_RAC_Form_App.RAC_Service.User CreateUser(SOA_RAC_Form_App.RAC_Service.User Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/CreateUser", ReplyAction="http://tempuri.org/IUsers/CreateUserResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.User> CreateUserAsync(SOA_RAC_Form_App.RAC_Service.User Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/GetUser", ReplyAction="http://tempuri.org/IUsers/GetUserResponse")]
        SOA_RAC_Form_App.RAC_Service.User GetUser(int UserdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/GetUser", ReplyAction="http://tempuri.org/IUsers/GetUserResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.User> GetUserAsync(int UserdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/UpdateUser", ReplyAction="http://tempuri.org/IUsers/UpdateUserResponse")]
        SOA_RAC_Form_App.RAC_Service.User UpdateUser(SOA_RAC_Form_App.RAC_Service.User Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/UpdateUser", ReplyAction="http://tempuri.org/IUsers/UpdateUserResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.User> UpdateUserAsync(SOA_RAC_Form_App.RAC_Service.User Entyity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/DeleteUser", ReplyAction="http://tempuri.org/IUsers/DeleteUserResponse")]
        SOA_RAC_Form_App.RAC_Service.User DeleteUser(int UserdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/DeleteUser", ReplyAction="http://tempuri.org/IUsers/DeleteUserResponse")]
        System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.User> DeleteUserAsync(int UserdId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersChannel : SOA_RAC_Form_App.RAC_Service.IUsers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersClient : System.ServiceModel.ClientBase<SOA_RAC_Form_App.RAC_Service.IUsers>, SOA_RAC_Form_App.RAC_Service.IUsers {
        
        public UsersClient() {
        }
        
        public UsersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOA_RAC_Form_App.RAC_Service.User[] ListUsers(SOA_RAC_Form_App.RAC_Service.UserRequest Request) {
            return base.Channel.ListUsers(Request);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.User[]> ListUsersAsync(SOA_RAC_Form_App.RAC_Service.UserRequest Request) {
            return base.Channel.ListUsersAsync(Request);
        }
        
        public SOA_RAC_Form_App.RAC_Service.User CreateUser(SOA_RAC_Form_App.RAC_Service.User Entyity) {
            return base.Channel.CreateUser(Entyity);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.User> CreateUserAsync(SOA_RAC_Form_App.RAC_Service.User Entyity) {
            return base.Channel.CreateUserAsync(Entyity);
        }
        
        public SOA_RAC_Form_App.RAC_Service.User GetUser(int UserdId) {
            return base.Channel.GetUser(UserdId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.User> GetUserAsync(int UserdId) {
            return base.Channel.GetUserAsync(UserdId);
        }
        
        public SOA_RAC_Form_App.RAC_Service.User UpdateUser(SOA_RAC_Form_App.RAC_Service.User Entyity) {
            return base.Channel.UpdateUser(Entyity);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.User> UpdateUserAsync(SOA_RAC_Form_App.RAC_Service.User Entyity) {
            return base.Channel.UpdateUserAsync(Entyity);
        }
        
        public SOA_RAC_Form_App.RAC_Service.User DeleteUser(int UserdId) {
            return base.Channel.DeleteUser(UserdId);
        }
        
        public System.Threading.Tasks.Task<SOA_RAC_Form_App.RAC_Service.User> DeleteUserAsync(int UserdId) {
            return base.Channel.DeleteUserAsync(UserdId);
        }
    }
}
